# Dockerfile References: https://docs.docker.com/engine/reference/builder/

# start from a the latest python image

FROM python:3.6-slim-buster
LABEL maintainer="Brian Grier <brinjgrier@gmail.com>"
LABEL version="0.1"

RUN pip install requests

RUN useradd -ms /bin/bash appuser

WORKDIR /home/appuser

COPY macaddress .macaddress
RUN chown appuser:appuser .macaddress

COPY getmacaddrowner.py getmacaddrowner.py
RUN chown appuser:appuser getmacaddrowner.py

USER appuser

# CMD python ./getmacaddrowner.py
ENTRYPOINT [ "python",  "getmacaddrowner.py" ]



